### PR TITLE
Made external dependencies optional to reduce output binary size

### PR DESCRIPTION
**Pull request by a-h**
I'm using a Splunk log forwarder from text files, but I want to use the log rotation feature and the cleanup feature that funnel provides.

The app imports a number of libraries to support other outputs such as S3, Elasticsearch, Kafka, Redis and InfluxDB which increase the size of the output binary. The Linux build output is 23MB, but a minimal build excluding the features is 12MB.

This pull request:
 * Adds build tags which can optionally disable unused features on a per-build basis.
 * Updates the `make release` output to also create a funnel_minimal-GOOS-GOARCH build output.

### CODE REVIEW

**Comment by agnivade** [comment]
This is perfect ! I would just request 2 things -
- Please add a section on the build tags below `Configuration` in the README.
- I am guessing you have already ran a quick sanity test on the minimal binary and confirmed that everything runs fine ? If not, I would request to do a quick check.

**Comment by a-h** [comment]
Thanks, I'll add the section.

I've done a sanity check on the binary, it's what I intend to run in production - I've been testing performance and log rotation, hence finding the difference between the defaults and config file. I was hoping to get away without having to add a config file to the server and just use the defaults. :grinning:

**Comment by agnivade** [comment]
>  I was hoping to get away without having to add a config file to the server and just use the defaults. 

That was the whole purpose ! 

And I think you have inadvertently pushed an unrelated commit in the same branch. Kindly take care of it :) (You fixed this while I was typing the comment :))

**Comment by agnivade** [comment]
LGTM :+1: . As a clean-up thing, I would request you to remove the lexical sorting commit and its revert commit altogether so that we have a clean commit tree. And also, please do a rebase from the master branch instead of merge, so that we can get rid of the merge commit. I like to have a clean and linear commit history :)

**Comment by a-h** [comment]
Thanks, you're forcing me to finally learn to be a considerate git user. :joy:

**Pull request merged**
